#spring:
#  datasource:
#    name: agy
#    url: jdbc:mysql://localhost:3306/agy_train
#    username: root
#    password: lowe110
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#  http:
#    multipart:
#      max-file-size: 2048Mb
#      max-request-size: 2048Mb
#    converters:
#      preferred-json-mapper: fastjson
#mybatis-plus:
#  mapper-locations: classpath*:ax/f4j/**/dao/*.xml
#  typeAliasesPackage: ax.f4j.**.entity
#  global-config:
#    id-type: 3
#    db-column-underline: false
#    refresh-mapper: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    lazyLoadingEnabled: true
#    multipleResultSetsEnabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
f4j:
  file:
    docPath: C:\bzaq\doc\
    videoPath: C:\bzaq\video\
    webPath: C:\bzaq\web\
  sql-performance-scan: false
